### ISSUE TITLE
About meta-regression

### ISSUE THREAD

**Issue by zhui126** [guido-s/netmeta#10]
Hi, Guido,
I wonder whether a meta-regression model will be added to this package? Meta-regression is helpful for adjusting for baseline imbalance, and you added this function in your meta package. The meta-regression now is only used in NMA with Bayesian methods, in the frequentist model, I wonder whether it is possible to do it?
Another question, will you consider adding a function to combine aggregate-level and individual-level data? Just like the matching adjusted indirect comparison (MAIC)?
Thank you for contribution to the netmeta package, it is very nice package.

Best wishes,
Hui

**Comment by guido-s** [comment]
Time to comment on this issue (after almost two years). We (still) intend to make meta-regression available in **netmeta**, however, we lack the time to do so.

We have no plans regarding the combination of aggregate-level and individual-level data.
