### ISSUE TITLE
Calculating the adjustment for funnel plots

### ISSUE THREAD

**Issue by holub008** [guido-s/netmeta#11]
In `funnel.netmeta`, only direct comparisons are used for centering observed effects: https://github.com/guido-s/netmeta/blob/2d6ab22b14872322c71d0dfcab725d244f5a14e5/R/funnel.netmeta.R#L401-L408

Based on the docs, this is derived from [Chaimani 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3789683/) and an earlier 2012 publication. The guidance offered:

> In the ‘comparison-adjusted’ funnel plot the horizontal axis presents the difference between the study-specific effect sizes from the corresponding comparison-specific summary effect 

Both papers go on to examples using only direct comparisons in estimating effects used in adjustment.

Is there a reason we shouldn't prefer including indirect evidence, i.e. using effect estimates from the NMA itself? e.g.

```R
for (i in seq_along(res$TE))
  res$TE.center[i] <- x$TE.common[treat1[i], treat2[i]] 

res$TE.adj <- res$TE - res$TE.center
```

If NMA assumptions hold, I would expect this to result in improved accuracy & comparability for trending, of observed effects. Perhaps this is unfounded, I couldn't find support in a brief literature search.

Thanks for your time, and as always, `netmeta`!

**Comment by guido-s** [comment]
This sound more like a question to Anna Chaimani and colleagues, I nevertheless try to answer it.

The decision to publish or not publish a study is based on the result of the individual study (if we only consider publication bias and not other small study effects). Accordingly, considering network instead of direct estimates in the funnel plot is counter-intuitive. This would, for example, mean that studies published in the future have an influence on the publication probability of a study.

**Comment by holub008** [comment]
You're right, I will float it by the authors. I posted here because I first encountered it in your code.

> studies published in the future have an influence on the publication probability of a study

I thiink that's already the case in this implementation, even using just direct evidence in the adjustment.

**Comment by guido-s** [comment]
I meant the following. The network estimate of A vs B would be based on direct evidence from A vs B and indirect evidence via all available loops. If you have a small network comparing A, B and C with older studies comparing A vs B and newer studies comparing A vs C and B vs C, the network estimate would contain older direct evidence and newer indirect evidence.
