### ISSUE TITLE
Is there some way to support your work?

### ISSUE THREAD

**Issue by Rscho314** [guido-s/netmeta#12]
Hi,

I've been using netmeta, and I'd like to support your effort. I don't have much time to spare writing code and probably don't have the chops to really contribute, unfortunately. So how about some financial contribution?

Do you have donations set up somewhere?

Best,
Raoul

**Comment by guido-s** [comment]
Hi Raoul,
Thank you for the nice words and your offer. We are lucky that we can work on **netmeta** during our working hours. The best way to support us is by citing **netmeta** in publications; see printout of R command `citation(package = "netmeta")`.
Best wishes,
Guido
