### ISSUE TITLE
Unable to calculate treatment effect and std err for certain studies

### ISSUE THREAD

**Issue by wanx4910** [guido-s/netmeta#18]
## Classification of issue

Please indicate whether you want to submit a

  - [x] bug report

## Summary

Was using the netmeta package to calculate treatment effect and its std error using the pairwise function on a long arm form and the most of the Te and seTe was not calculated and there was no error messages stating why they were not calculated.

Input for pairwise:
Study	treatment	r	       N
ZB 2014	DZ+WM	        60           200
ZB 2014	WZ	                83	       200
LYK 2015	ZZ	                48.4	       32
LYK 2015	ZY	                59.9	       32
W 2015	ZZ	                27.3	       43
W 2015	WM	                34.2	       41
LC 2017	DZ+WM	        71.58      53
LC 2017	WM	                93.36      38
S 2018	DZ+WM	        70.5	       53
S 2018	WM	                92.5	       52
D 2018	ZZ+WM	        26.11      32
D 2018	WM	                34.31      32
H 2021	DZ+WM	        72.6	       44
H 2021	WM	                117	       44
C 2023	ZZ+WM	        103.74    43
C 2023	WM	                132.58    43

After pairwise function output:
studlab	treat1	treat2	TE	                         seTE	        event1	n1	     event2	n2
ZB 2014	DZ+WM	WZ	       -0.5039645334	0.210724287	60	        200	     83	        200
LYK 2015	ZZ	        ZY			                                                48.4	        32	     59.9	        32
W 2015	ZZ	        WM	       -1.062077042	        0.5259495164	27.3	        43	     34.2	        41
LC 2017	DZ+WM	WM			                                                71.58	53	     93.36	        38
S 2018	DZ+WM	WM			                                                70.5	        53	     92.5	        52
D 2018	ZZ+WM	WM			                                                26.11	32	     34.31	        32
H 2021	DZ+WM	WM			                                                72.6	        44	     117	        44
C 2023	ZZ+WM	WM			                                                103.74	43	     132.58	43

## Additional information
Silent error when not calculating Te and seTe using the pairwise function on a long arm form study

```r
data = read_excel("/data.xlsx", sheet = 1)
p5 <- pairwise(treatment, event = r, n = N, studlab = Study, data = data, sm = "OR")

```

### Environment
  - macOS
  - RStudio 2023.12.1+402
  - netmeta 2.9-0

**Comment by guido-s** [comment]
This is no bug, but a problem with your data: several numbers of events are larger than the group sample sizes, e.g., in the LYK study.

You will get information on the calculation problems if you use argument `warn = TRUE` in `pairwise()`.
