### ISSUE TITLE
I cant run netmeta macOs samoma, and i get this issue, please does any body have a solution?

### ISSUE THREAD

**Issue by gmvidalmd** [guido-s/netmeta#20]
Loading required package: meta
Loading required package: metadat
Loading 'meta' package (version 7.0-0).
Type 'help(meta)' for a brief overview.
Readers of 'Meta-Analysis with R (Use R!)' should install
older version of 'meta' package: https://tinyurl.com/dt4y5drs
Loading 'netmeta' package (version 2.9-0).
Type 'help("netmeta-package")' for a brief overview.
Readers of 'Meta-Analysis with R (Use R!)' should install
older version of 'netmeta' package: https://tinyurl.com/kyz6wjbb

**Comment by guido-s** [comment]
I am developing and using R packages **meta** and **netmeta** on a Macbook with macOS Sonoma. Accordingly, your problem is not due to the OS.
